# Generated by Django 3.1.4 on 2020-12-27 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=100)),
                ('Organization', models.CharField(max_length=100)),
                ('Date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
